apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: omkar0707/jenkins:latest  # Replace with your actual image name and tag
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80          # External access port
      targetPort: 3000  # Matches the container port exposed in the Deployment
      nodePort: 32000  # Assign a unique port for external access (optional)
  type: NodePort
